### ISSUE TITLE
Edit buttons split when on MediaWiki 1.40+

### ISSUE THREAD

**Issue by BCMonomial** [StarCitizenTools/mediawiki-skins-Citizen#812] opened 2024-03-16 14:21 UTC
## Describe the Bug
We assume that some CSS class changes happened in MediaWiki higher than 1.40, causing the edit buttons not combined in Citizen style as before if VisualEditor is activated.
![image](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/156907600/60e53547-ea2f-4332-81b5-b5ed29f81baa)

Steps to reproduce:
On MediaWiki 1.41.0 (Presumably any version higher than 1.40):
1. Go to 'Special:Preferences'
2. Activate VisualEditor
3. See changes in pages

## System
 - MediaWiki 1.41.0
 - Citizen 2.10.1
 - PHP version 8.2.12 (fpm-fcgi)
 - VisualEditor 0.1.2

**Comment by alistair3149** [comment] 2024-03-18 01:25
Thanks for the report! Do you have a demo page for the issue?

**Comment by BCMonomial** [comment] 2024-03-18 08:09
> Thanks for the report! Do you have a demo page for the issue?

I'm glad to but I don't want to put our address here publicly, and our wiki has restricted access on editing (users can't edit without logged in, and registration can only be done by admins). If possible can I provide you our address and a test account privately (like via a publicly available email of yours or other ways)?

**Comment by alistair3149** [comment] 2024-03-19 22:59
For the section link, it is likely something that changed upstream ([T346944](https://github.com/wikimedia/mediawiki/commit/9ef28e8e0e25442a43b9c05980f76f6c05835959)).

As for the merged edit buttons, I can't reproduce it on a MW 1.41 wiki. not sure what's going on but it could be related to some upstream changes as well.

For both issue, it will take some time to investigate and fix since I don't have a MW 1.41 dev environment right now and there are a lot of changes on skins in general.

**Comment by BCMonomial** [comment] 2024-03-20 17:09
> For the section link, it is likely something that changed upstream ([T346944](https://github.com/wikimedia/mediawiki/commit/9ef28e8e0e25442a43b9c05980f76f6c05835959)).
> 
> As for the merged edit buttons, I can't reproduce it on a MW 1.41 wiki. not sure what's going on but it could be related to some upstream changes as well.
> 
> For both issue, it will take some time to investigate and fix since I don't have a MW 1.41 dev environment right now and there are a lot of changes on skins in general.

Thanks for the update! Please let me know if there's anything I can be helpful with.

**Comment by alistair3149** [comment] 2024-04-24 02:38
Okay I finally figured out the issue.
This is caused by an [upstream bug](https://phabricator.wikimedia.org/T287622) where extension hooks can run after skin hooks (e.g. VE adds the edit button after Citizen modifies it, so Citizen does not know there is a VE button).

The solution is to load Citizen after all extensions.
You can achieve this by putting `wfLoadSkin( 'Citizen' );` in your `localsettings.php` after all the extensions.

**Closed** 2024-04-24 02:39 UTC
Labels: wontfix

**Comment by BCMonomial** [comment] 2024-05-06 15:41
Sorry to reopen this issue but... well, something weirder is happening here. We have upgraded to the latest 2.13.2 version, and we moved `wfLoadSkin( 'Citizen' );` at the bottom of the `localSettings.php`.

We see the changes that the section edit buttons are now fixed, but the main edit button is somehow like this.

![image](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/69715347/6480e16b-f151-49c1-ae0f-940f3f115ad1)

Have no idea what's going on here. Below is our full list of extensions:

![image](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/69715347/e26eaddf-732c-4de7-92a8-e7f6f2252876)
![image](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/69715347/92275b3c-6cc3-44cb-ae08-3abcda158cba)
![image](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/69715347/533223be-4cb8-4e83-88aa-80dfd0653676)
