### ISSUE TITLE
ULS personal tool is not rendered for some wiki

### ISSUE THREAD

**Issue by lens0021** [StarCitizenTools/mediawiki-skins-Citizen#425] opened 2022-02-17 19:36 UTC
## Describe the Bug
Using citizen skin, there is no UniversalLanguageSelector on the personal tool portlet.

1. Go to 'https://wordles.miraheze.org/wiki/Special:BlankPage?useskin=citizen'
2. Click on 'Toggle personal menu' (👤)

## Expected Behavior
`<li id="ca-uls" …>…</li>` should be included, like on vector (https://wordles.miraheze.org/wiki/Special:BlankPage?useskin=vector) or Star Citizen Wiki(https://star-citizen.wiki/)

## System
 - MediaWiki version: 1.37.1
 - Server OS: Debian Bullseye<sup>[[1]](https://github.com/miraheze/puppet/blob/99e51a94c358b694eeec5f4d102e08453425a885/README.md?plain=1#L29)</sup>
 - Installed extensions and versions
   - [UniversalLanguageSelector](https://www.mediawiki.org/wiki/Extension:UniversalLanguageSelector): 95f27a3
 - PHP version: 7.4.25 (fpm-fcgi)

**Comment by alistair3149** [comment] 2022-02-19 20:02
Is the issue isolated to logged in users? I have noticed this issue before but wasn't able to pinpoint the cause.

**Comment by lens0021** [comment] 2022-02-20 04:54
Anonymous users also do not have the ULS. I suspect the changes of personal tools of MW1.36 are the cause.

**Comment by AlanYe-Dev** [comment] 2022-05-16 01:23
I have the same issue

### System
* MediaWiki version: 1.37.2
* Server OS: Ubuntu 20.04 LTS
* Installed extensions and versions
** UniversalLanguageSelector: 729194a
* PHP version: 7.3.31 （fpm-fcgi)

**Comment by alistair3149** [comment] 2022-05-16 03:38
I can reproduce the issue now and am looking into it.

**Comment by alistair3149** [comment] 2022-05-17 02:44
I couldn't get ULS from the personal tools for some reason on 1.39.
@lens0021 Do you have some idea on what the issue might be? I couldn't figure it out.

**Comment by alistair3149** [comment] 2022-10-02 16:34
Just an update on the issue.
I am not sure what is going on with it but it should be fixed when we refactor the skin for 1.39,
which will also tackle the personal menu. It should be ready by the time 1.39 releases.

**Comment by alistair3149** [comment] 2022-12-01 19:15
No longer relevant in 1.39

**Closed by alistair3149** 2022-12-01 19:15 UTC
Labels: bug, help wanted

**Comment by ManuelHaas** [comment] 2023-02-13 22:25
Using current citizen skin (2.40), there is no UniversalLanguageSelector on the personal tool portlet neither for anonymous nor registered users.
Using mediawiki 1.39.1
