### ISSUE TITLE
Exception MW1.37.2 - php7.4 

### ISSUE THREAD

**Issue by g7sim** [StarCitizenTools/mediawiki-skins-Citizen#483] opened 2022-06-25 14:00 UTC
## Describe the Bug
My spiritwiki.info functions with other Skins ( the exception comes not with php 8.019  )

Original exception: [YrcTxwxA2rkFEu12kc1GuAAAC34] /index.php?title=Hauptseite&useskin=citizen IntlException: Constructor failed
Backtrace:
from /mnt/web411/a1/95/51471234/htdocs/wiki1314/mediawiki-1372/skins/Citizen/includes/Partials/Drawer.php(180)
#0 /mnt/web411/a1/95/51471234/htdocs/wiki1314/mediawiki-1372/skins/Citizen/includes/Partials/Drawer.php(180): NumberFormatter->__construct()

This happens both - with the newest 1.17 and with the master

**Comment by alistair3149** [comment] 2022-06-25 19:36
Duplicate of #474.
There is an issue with your ICU/php-intl installation. You can try to update it and see if it will fix it, or you can use set `$wgCitizenUseNumberFormatter` to `false`.

**Closed by alistair3149** 2022-06-25 19:36 UTC
Labels: duplicate
