### ISSUE TITLE
Screen styles of Table of Content is loaded on print mode

### ISSUE THREAD

**Issue by streetclaw** [StarCitizenTools/mediawiki-skins-Citizen#178] opened 2020-08-13 14:29 UTC
## Describe the Bug
The print version is broken when the navigation is shown. The navigation is placed over the content on all pages. The text behind the navigation is hard to read.

1. Go to a page with navigation. Example: https://starcitizen.tools/ROC
2. Print the page (navigation)

## Expected Behavior
Navigation is placed on one page and not placed over any content.

## System
- starcitizen.tools wiki
- Firefox 79

**Comment by alistair3149** [comment] 2020-08-17 02:31
I'm not able to reproduce it, do you have a screenshot for it?

**Comment by streetclaw** [comment] 2020-08-19 16:20
<img width="409" alt="print" src="https://user-images.githubusercontent.com/21123777/90662327-85e32500-e248-11ea-9360-2dbd7cae513d.png">

System: macOS

**Comment by alistair3149** [comment] 2021-03-08 19:59
Fixed in 469a2fd

**Closed by alistair3149** 2021-03-08 19:59 UTC
Labels: bug
