### ISSUE TITLE
Text title instead of logo

### ISSUE THREAD

**Issue by tim1mike** [StarCitizenTools/mediawiki-skins-Citizen#226] opened 2021-01-17 02:24 UTC
## Describe the Bug
I just installed 1.2.2 version of the skin and I noticed that my .svg logo doesn't show up after I opened the menu, I see the site title instead and this warning message in the console:

`The resource https://mysite.com/resources/assets/logo.svg was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.`

MyLocalSettings.php says:
```
$wgLogo = "$wgResourceBasePath/resources/assets/logo.svg";
$wgLogos = [ 'svg' => "$wgLogo" ];
```

## System
 - MediaWiki version v.1.35.1
 - Server OS: Ubuntu 18.04
 - PHP version 7.4.13 (apache2handler)

Thanks for any help

**Comment by alistair3149** [comment] 2021-01-17 04:08
Will look into it. The logo code was recently refactored so it might be where the issue is.

**Comment by alistair3149** [comment] 2021-01-19 16:48
Merged patch in 2c93c68.
Would you mind to verify if it is patched?

**Comment by alistair3149** [comment] 2021-01-19 21:54
Close for now, reopen if the issue perists

**Closed by alistair3149** 2021-01-19 21:54 UTC
Labels: bug

**Comment by tim1mike** [comment] 2021-01-25 00:15
It works well, thanks
The only thing is wordmark's visible as well, so I just add `display:none;` to hide `.mw-logo-container`
