### ISSUE TITLE
Recent Changes page is empty

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [StarCitizenTools/mediawiki-skins-Citizen#384] opened 2021-05-11 18:14 UTC
Other skins are working correctly.
![image](https://user-images.githubusercontent.com/45261195/117864739-b6338d80-b2c7-11eb-856f-7195ddea3b0f.png)

System Information:
MediaWiki 1.35.2
Docker Debian 10
PHP 7.4.16
Chinese Language

**Comment by alistair3149** [comment] 2021-05-12 03:09
Thanks for the report! I have been trying to hunt down the issue as it happens rarely and it is likely related to the skin. Do you happen to have any server logs that is related, I couldn't find anything useful client-side.

**Comment by Aira-Sakuranomiya** [comment] 2021-05-12 09:14
[php-fpm:access] 127.0.0.1 -  12/May/2021:17:10:57 +0800 "POST /api.php" 200 /app/api.php 235.862 8192 101.75%
172.17.0.1 - - [12/May/2021:17:10:57 +0800] "POST /api.php HTTP/1.0" 200 41 "https://otomad.wiki/Special:%E6%9C%80%E8%BF%91%E6%9B%B4%E6%94%B9?hidebots=1&limit=500&days=30&enhanced=1&urlversion=2" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 Edg/90.0.818.56"
[php-fpm:access] 127.0.0.1 -  12/May/2021:17:10:57 +0800 "POST /api.php" 200 /app/api.php 242.377 4096 99.02%
172.17.0.1 - - [12/May/2021:17:10:58 +0800] "POST /api.php HTTP/1.0" 200 41 "https://otomad.wiki/Special:%E6%9C%80%E8%BF%91%E6%9B%B4%E6%94%B9?hidebots=1&limit=500&days=30&enhanced=1&urlversion=2" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 Edg/90.0.818.56"

**Comment by Aira-Sakuranomiya** [comment] 2021-05-12 10:50
![QQ截图20210512184932](https://user-images.githubusercontent.com/45261195/117963362-e07e5d00-b352-11eb-8f94-16a1a1cd8f7d.jpg)
If i set this to 7, everything will be ok
If i set this to 30, it will be empty

**Comment by alistair3149** [comment] 2021-05-12 12:43
Thanks for the log. It looks normal. Since I can't reproduce the issue on my end, I'm unable to pin down what the cause can be. Would you mind to set `$wgCitizenEnableCollapsibleSections` to false and see if it fixes it? 

And if you have another wiki installation that can reproduce the issue, would you mind to send me the PHP error log after adding this to localsettings:
```php
error_reporting( E_ALL );
ini_set( 'display_errors', 1 );
```

**Comment by Aira-Sakuranomiya** [comment] 2021-05-12 13:27
set `$wgCitizenEnableCollapsibleSections` to false fixed that

**Comment by alistair3149** [comment] 2021-05-12 14:33
Now would you mind to re-enable the config to check if the issue appears again? Trying to lock down if it is related to the config.

**Comment by Aira-Sakuranomiya** [comment] 2021-05-12 15:59
okay i tested it is not related to the `$wgCitizenEnableCollapsibleSections` :(

**Comment by Aira-Sakuranomiya** [comment] 2021-05-12 16:01
This seems to be related to the number of edits displays

**Comment by Aira-Sakuranomiya** [comment] 2021-05-12 16:01
![image](https://user-images.githubusercontent.com/45261195/118007042-5e0b9280-b37e-11eb-992a-2df19f058c08.png)
![image](https://user-images.githubusercontent.com/45261195/118007085-65cb3700-b37e-11eb-866b-93c2beca5d7a.png)

**Comment by alistair3149** [comment] 2021-05-12 16:19
> okay i tested it is not related to the `$wgCitizenEnableCollapsibleSections` :(

Thanks it is the confirmation I needed for now. It might take a while to debug since I don't have access to a production wiki that can reproduce the issue.

**Comment by Aira-Sakuranomiya** [comment] 2021-05-13 10:10
it seems your wiki can reproduce this issue

use these links to reproduce:
* https://dev.starcitizen.tools/Special:RecentChanges?hidebots=1&translations=filter&limit=500&days=90&enhanced=1&urlversion=2
* https://star-citizen.wiki/Spezial:Letzte_%C3%84nderungen?hidebots=1&limit=500&days=90&enhanced=1&urlversion=2

This error appears to occur when too much content is going to be displayed

**Comment by alistair3149** [comment] 2021-05-13 12:40
Yes it did resurfaced again. Should have a potential fix today that hopefully fix the issue.

**Comment by alistair3149** [comment] 2021-05-13 13:51
Would you mind to check if the latest patch resolve the issue?

**Comment by Aira-Sakuranomiya** [comment] 2021-05-13 16:37
yes! it seems to be fixed!!!!

**Comment by alistair3149** [comment] 2021-05-13 16:59
Thanks for the confirmation! Closing the issue now

**Closed by alistair3149** 2021-05-13 16:59 UTC
Labels: bug
