### ISSUE TITLE
Links in search result not clickable in mobile safari

### ISSUE THREAD

**Issue by octfx** [StarCitizenTools/mediawiki-skins-Citizen#410] opened 2021-11-22 20:32 UTC
## Describe the Bug
When using the search and trying to click a result in mobile safari, nothing happens.  
(When holding down and selecting "Open in Background" the link will open)

1. Go to Search
2. Input a term
3. Try to click a link

## Expected Behavior
Link opens after clicking it

## System
 - MediaWiki version 1.35.3
 - Latest Citizen version

**Comment by alistair3149** [comment] 2021-11-27 19:12
Thanks for the report! What page is that on? And what search and result are you referring to?

**Comment by octfx** [comment] 2021-11-27 22:40
For example trying to click anywhere in the highlighter area just closes the results list without opening the page.
<img width="671" alt="search_bug_ios png" src="https://user-images.githubusercontent.com/6594492/143722393-9e70e395-2e7e-4668-b031-340908139a16.png">

**Comment by alistair3149** [comment] 2021-11-30 15:51
Looks like Safari has problem with the suggestion listing going `display: none`

**Comment by octfx** [comment] 2021-11-30 16:51
I think this may be a duplicate of #404

**Comment by alistair3149** [comment] 2021-11-30 22:16
Duplicate of #404

**Closed by alistair3149** 2021-11-30 22:16 UTC
Labels: bug
