### ISSUE TITLE
Add support for DiscussionTools

### ISSUE THREAD

**Issue by LuciferianThomas** [StarCitizenTools/mediawiki-skins-Citizen#665] opened 2023-06-20 02:32 UTC
## The Problem
There doesn't appear to be support for [DiscussionTools](https://www.mediawiki.org/wiki/Extension:DiscussionTools) on the Citizen currently, leading to broken styles for topic subscription, and original MediaWiki styles for the reply feature.
![image](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/31434911/53b928d1-0f4c-48fe-9f24-94e415fa789b)
![image](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/31434911/a4929b30-f55b-4dd1-a39c-008b3776261a)

## The Solution
I'm not familiar with skins, so I can't actively contribute to make it work, but I hope support could be added for DiscussionTools features.
* Topic subscription to be added alongside (to the right of) the edit buttons, with a bell (https://commons.wikimedia.org/wiki/File:OOjs_UI_icon_bell.svg) to replace the "subscribe" text, and a bell with a slash to replace "unsubscribe".
* Possibly an arrow icon after each comment replacing the "reply" text.

**Comment by alistair3149** [comment] 2023-06-20 03:43
Thanks for the report! I addressed the issue with the subscribe button in 638cca92cf4787d4ab001cc12d355b8db37d47ee.
As for the reply button, I will eventually look into revamping the DiscussionTools styles but I don't have a timeline yet.

**Comment by LuciferianThomas** [comment] 2023-06-20 10:01
Thanks for the quick response! The bell also triggers the collapse title feature as in https://meta.wikitide.com/wiki/Community_portal, would it be possible to move it to after the edit icons?

**Comment by Dringsim** [comment] 2023-06-20 17:05
> Thanks for the quick response! The bell also triggers the collapse title feature as in https://meta.wikitide.com/wiki/Community_portal, would it be possible to move it to after the edit icons?

Edit icons also trigger collapsing...

**Comment by LuciferianThomas** [comment] 2023-06-20 17:08
> > Thanks for the quick response! The bell also triggers the collapse title feature as in https://meta.wikitide.com/wiki/Community_portal, would it be possible to move it to after the edit icons?
> 
> Edit icons also trigger collapsing...

Cannot reproduce, both of my VE edit icons do not trigger collapsing.

**Comment by alistair3149** [comment] 2023-06-20 18:19
> > Thanks for the quick response! The bell also triggers the collapse title feature as in https://meta.wikitide.com/wiki/Community_portal, would it be possible to move it to after the edit icons?
> 
> Edit icons also trigger collapsing...

Yeah I think Luciferian config is different because he is using the option where both visual and source edit buttons are visible. In that mode, the subscribe button is pushed to the left. I'll look more into it but I don't have a working setup at the moment. Is WikiTide/Forge on the latest version?

**Comment by alistair3149** [comment] 2023-06-20 19:19
I kind of addressed the layout issue with f74244ff4682b5bf380bedc5a124717d2350b364, but I don't have time to have an in-depth look into the extension yet, perhaps in these two weeks.

**Comment by LuciferianThomas** [comment] 2023-06-22 15:20
As a side note: the "subscribe" link normally floats to the right of headers, but it only appears on the left when it's on Citizen. I can see (via DevTools) that is has float:right on it, but it just doesn't work. I'm not sure if the latest fix resolves this oversight, so commenting to ask.

**Comment by LuciferianThomas** [comment] 2023-06-23 06:24
I also just noticed that the icon is not updated on dark theme, giving this:
![image](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/31434911/23233601-9500-46d2-98ac-b59ef5fe51e8)

**Comment by LuciferianThomas** [comment] 2023-07-11 11:44
@alistair3149 ?

**Comment by alistair3149** [comment] 2023-07-11 19:46
It should be fixed a few weeks ago, would you mind to verify it?

**Comment by alistair3149** [comment] 2024-05-08 06:14
Confirmed working on multiple wikis, closing the issue

**Closed by alistair3149** 2024-05-08 06:14 UTC
Labels: enhancement
