### ISSUE TITLE
StructuredDiscussions doesn't work with Citizen on MW 1.40+

### ISSUE THREAD

**Issue by dringsim** [StarCitizenTools/mediawiki-skins-Citizen#711] opened 2023-08-25 04:13 UTC
## Describe the Bug
A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.

1. Open Special:EnableStructuredDiscussions and create a flow board:
![image](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/57343841/4283d36d-22b0-4a30-bb25-701569088da4)
2. On the new board, create several topics:
![image](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/57343841/20cf20e2-9f3a-42f5-8916-05224de59c0c)
3. Refresh (see http://dringsim.rf.gd/w/index.php/Testflow):
![image](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/57343841/c935d7e0-327f-41ba-94c2-d334e7284544)

## Expected Behavior
StructuredDiscussions should work just like on other skins (http://dringsim.rf.gd/w/index.php/Testflow?useskin=vector):
![image](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/57343841/2a3e87b8-7755-4738-a8d1-a19b2e2c21b6)
StructuredDiscussions works fine with Citizen on MW 1.39 (Miraheze), and with default skins on MW 1.40 and MW 1.41 alpha (WMF).

## System
_Please complete the following information:_
 - MediaWiki: 1.40.0
 - PHP: 7.4.8
 - Citizen: 2.8.0
 - StructuredDiscussions: 1.2.0 (04dfdd6)
The server is hosted by InfinityFree.

**Comment by Dringsim** [comment] 2023-08-25 09:04
Updated but still broken

**Comment by alistair3149** [comment] 2023-08-25 23:31
The page is missing some RL modules (more specifically `ext.flow.styles.base`), which prevented the loading of some of the default styles of StructuredDiscussion. I am not sure what exactly caused it though, seems there are some issues with the database connection limit

**Comment by Dringsim** [comment] 2023-08-26 15:09
The HTML structure seems malformed: 
![图片](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/57343841/e21e3308-502d-467d-b6ea-c4c0697169a1)
compare Vector:
![图片](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/57343841/4b33ab90-a8cb-403e-bf12-3a030f4d407a)

**Comment by alistair3149** [comment] 2023-08-26 18:49
Yeah I realised the HTML structure is malformed too, but Citizen doesn't affect the HTML of the extension. It might be something else but I'm not sure

**Comment by felipeforte** [comment] 2024-09-03 17:28
This should probably be reopened. I believe Citizen skin is somehow affecting the HTML structure of the flow pages.
Vector:
![image](https://github.com/user-attachments/assets/d5cadf65-f199-458a-8bfa-8f717885d277)
Citizen...:
![image](https://github.com/user-attachments/assets/a7b0a65f-1034-4527-8193-287b565392a7)

The problem also began as soon as we updated the theme of the website.

**Comment by alistair3149** [comment] 2024-09-03 18:10
Do you have a live demo of the page? It looks like that there are some missing styles.

**Comment by felipeforte** [comment] 2024-09-04 00:10
Absolutely: https://en.prolewiki.org/wiki/Talk:Communist_Party_of_the_United_States_of_America

You can see there is a PHP error in load.php style related to the Flow extension. But why would it happen only on the Citizen skin? And more, why would it happen only on a later version of Citizen...? (currently 2.27, previously 2.10)

**Comment by felipeforte** [comment] 2024-09-04 18:19
Thank you for looking into this. After applying the patch, the problem unfortunately persists. I recommend not closing the issue so soon, other users may be experiencing similar issues...

I'm not certain the problem with our MediaWiki instance is too particular, if you have any idea that could point us in the right direction, it'll be appreciated. The only tips I can give is based on the PHP error presented in the site's styles:

``Less_Exception_Compiler: error evaluating function `lighten` The first argument to lighten must be a color index: 194 in anchors.less``

`Problematic modules: {"ext.flow.styles.base":"error"}`

**Comment by alistair3149** [comment] 2024-09-04 19:16
It is definitely isolated to the Citizen skin, but the error log isn't pointing to anything that exists within the skin.
It might take some time to fix since I couldn't get the extension working locally, but I am looking into it.

**Comment by alistair3149** [comment] 2024-09-11 16:30
Seems to be related to https://phabricator.wikimedia.org/T357740

Still I don't know why the LESS mixins would have access to Citizen skinstyles, as we didn't touch the LESS variables...

**Comment by alistair3149** [comment] 2024-09-11 16:38
Unfortunately it is an upstream extension issue that I'm not able to workaround without significantly breaking the skin's color definition. The issue is fixed on 1.42 version of Flow.

In order to fix this, you can either update to MW 1.42 or backport the related fixes manually to the extension: 
1. https://github.com/wikimedia/mediawiki-extensions-Flow/commit/1fcbe1415cdebfd0141671194a8113280cb32990
2. https://github.com/wikimedia/mediawiki-extensions-Flow/commit/e8857c8f362ec5e93d481c008a2931f34b807e23

**Comment by felipeforte** [comment] 2024-09-23 12:24
That was precisely the issue! Thank you so much for looking into it, the problem wasn't even related to Citizen after all.

**Closed** 2024-10-23 22:23 UTC
Labels: bug, wontfix
