### ISSUE TITLE
VisualEditor incompatibilities

### ISSUE THREAD

**Issue by LewisTehMinerz** [StarCitizenTools/mediawiki-skins-Citizen#103] opened 2020-05-02 09:20 UTC
## Describe the Bug
VisualEditor *mostly* works on the Citizen theme, however there are a couple incompatibilities. Most notably:
![image](https://user-images.githubusercontent.com/8019327/80860207-24c62000-8c5e-11ea-8209-b7b0ec527f90.png)
![image](https://user-images.githubusercontent.com/8019327/80860224-3dced100-8c5e-11ea-87d4-9de1124eb1fc.png)

## Steps to reproduce the behavior
1. Install Citizen theme
2. Install VisualEditor (w/ Parsoid)
3. Go to a page you can edit

## Expected Behavior
Full compatibility with VisualEditor.

## System
_Please complete the following information:_
 - MediaWiki version [e.g. v1.33.1]: 1.34.1
 - Server OS: [e.g. Debian 10] Ubuntu Server 19.04
 - Installed extensions and versions [e.g. SemanticMediaWiki 3.0, WikiSEO 2.3.1, etc.] Nuke 1.3.0, Renameuser, CodeEditor, VisualEditor 0.1.1 (74116a7), WikiEditor 0.5.2, Cite 1.0.0, OpenGraphMeta 0.5.5 (0a61e8e), ParserFunctions 1.6.0, Scribunto, Description2 0.4.1 (2fd4f08)
 - PHP version [e.g. v7.2.19-0ubuntu0.18.04.2] 7.2.22-1+ubuntu19.04.1+deb.sury.org+1 (fpm-fcgi)

**Comment by alistair3149** [comment] 2020-05-02 21:15
I can't reproduce the bug on my side. Do you have a live demo and what's the version for the Citizen skin?

**Comment by LewisTehMinerz** [comment] 2020-05-03 12:02
I don't have a public live demo, the wiki I used was my testing wiki I run locally, but the version is 0.7.4 (latest on MediaWiki's site). I got a replication by installing the skin from scratch and installing VisualEditor (fully, of course) without changing any options.

My current workaround is to set `$wgVisualEditorUseSingleEditTab` to true so VisualEditor only uses one edit tab, and as such it does not put the labels on.

**Comment by alistair3149** [comment] 2020-05-15 16:20
Would you mind to show me the DOM structure/HTML of the text element and also a few levels of their parents? With that I should be able to put out a fix for it in master.

**Comment by LewisTehMinerz** [comment] 2020-05-15 19:05
For which part sorry? The tabs or the VisualEditor toolstrip overlap?

**Comment by alistair3149** [comment] 2020-05-17 22:01
The tabs. I am looking into the toolstrip overlap bug and it will be fixed in a hotfix soon.

**Comment by LewisTehMinerz** [comment] 2020-05-18 16:24
Ah, yeah we restrict it to logged in users only on the skin since those are the only people who can edit.

Here's the structure for the page tools: https://haste.friz.dog/ia2fwX81Au.html

**Comment by alistair3149** [comment] 2020-05-18 17:24
Closed as both bugs are fixed

**Closed by alistair3149** 2020-05-18 17:24 UTC
Labels: bug
