### ISSUE TITLE
Footer messages can't be changed

### ISSUE THREAD

**Issue by forteller** [StarCitizenTools/mediawiki-skins-Citizen#396] opened 2021-08-03 22:56 UTC
## Describe the Bug
Hi. Thank you for an amazing skin! 

I'm using Citizen on one of my wikis at Miraheze. I asked them first, and got told it was probably a bug upstream.

In the footer there are two messages saying edit this message at … and then the top one says MediaWiki:Citizen-footer-desc and the bottom one says MediaWiki:Citizen-footer-tagline. I've edited both, but still the same "edit this message" messages are still there in the footer. My wiki is in Norwegian, and the default messages in the footer is also in Norwegian, if that's relevant.

At Miraheze they said I should try adding /no at the end of the MediaWiki:Citizen-footer-desc and MediaWiki:Citizen-footer-tagline. In the /no pages the same "edit this message" message in Norwegian was, but editing them there still changed nothing in the footer.

1. See default messages in footer
2. Go to MediaWiki:Citizen-footer-desc and -footer and edit the pages
3. See that the same default messages are still in the footer

## Expected Behavior
Footer 

## System
Not sure how to get all of this info, except that they use MediaWiki version 1.36, from Miraheze. Let me know if you need it, and I'll find out!

Thank you!

**Comment by alistair3149** [comment] 2021-08-03 23:55
Thanks for letting me know! Would you mind to try edit `MediaWiki:Citizen-footer-tagline/nn` on your wiki and check if it works? The language code for Norwegian should be `nn` instead of `no`.

**Comment by forteller** [comment] 2021-08-04 14:47
Thanks!

So, nn didn't work either, but that opened my eyes to the actual solution. So, there are two versions of written Norwegian: Nynorsk and Bokmål. Any type of Norwegian is shortened `no`, while Nynorsk is `nn` and Bokmål is `nb`. So I tried /nb, and that worked!

So I guess there's no actual bug after all, but I would suggest that the translated version of the "edit this message" messages should include the relevant language code in the message (`/xx`), so that other's won't have the same issue as me. :)

**Comment by alistair3149** [comment] 2021-08-05 15:58
Thanks for the feedback. I incorporated the language code into the message and also make it into a wikilink. Closing it since it is not a bug and also the feature is implemented.

**Closed by alistair3149** 2021-08-05 15:58 UTC
Labels: bug
