### ISSUE TITLE
Various header icon issues

### ISSUE THREAD

**Issue by eshagh79** [StarCitizenTools/mediawiki-skins-Citizen#363] opened 2021-05-04 05:17 UTC
Hello.
The previous problem has not been solved yet.

You changed my commit a bit, and maybe that didn't fix the problem.

Please check it again

There is another problem in the dark mode that when we go to the help option, its color turns black and is not visible, while in other links it is not so and they change to white.
![Screenshot from 2021-05-04 09-42-07](https://user-images.githubusercontent.com/52137191/116963273-a7444e00-acbd-11eb-837a-cb0daa5bab98.png)

**Comment by alistair3149** [comment] 2021-05-04 12:41
I know why it didn't work, the checkbox selector was not inside the `#search`. As for the other issue, I'll look into it

**Comment by eshagh79** [comment] 2021-05-04 14:31
In fact, I did not understand what you meant. Because my mother tongue is not English.

I changed the magnifying glass style a bit more in the search box. I think this is better.

Please check it.
![Screenshot_2021-05-04 Fahrzeuge](https://user-images.githubusercontent.com/52137191/117019898-1c8a4000-ad0b-11eb-91e3-767d0e0c219a.png)

After the changes
![Screenshot_2021-05-04 Preferences - ویکی شخصی من](https://user-images.githubusercontent.com/52137191/117019922-23b14e00-ad0b-11eb-9267-4b6d7b18e798.png)
![Screenshot_2021-05-04 Preferences - ویکی شخصی من(1)](https://user-images.githubusercontent.com/52137191/117019945-290e9880-ad0b-11eb-9b5e-122c4b4d4979.png)

**Comment by alistair3149** [comment] 2021-05-04 17:36
Both issues should be fixed in master now, would you mind to take a look?

**Comment by eshagh79** [comment] 2021-05-05 04:19
This was the first problem I saw.
The settings icon has been moved down.
Find out in the attached image.
![Uploading Screenshot_2021-05-05 ویکی شخصی من.png…]()

**Comment by alistair3149** [comment] 2021-05-05 04:24
> This was the first problem I saw.
> The settings icon has been moved down.
> Find out in the attached image.
> ![Screenshot_2021-05-05 ویکی شخصی من](https://user-images.githubusercontent.com/52137191/117096649-fe5e2780-ad7e-11eb-96e6-37057d9154b4.png)

It could be cached, do a hard refresh and see if it is still there. And if it is still an issue, what is the browser and OS you're using?

**Comment by eshagh79** [comment] 2021-05-05 06:02
I am using Firefox version (88.0+build2-0ubuntu0.20.10.1).
on ubuntu 20.04.

Probably this problem with my system.
Because my system repositories are for Ubuntu 20.10. I know this is wrong because I ran out of internet updates and have not yet completed the update.

I also tested it on the Opera browser and it did not show any settings at all.

**Comment by eshagh79** [comment] 2021-05-05 06:11
in my idea, it is more beautiful if the magnifying glass icon is out of the default mode for right-to-left languages.

I sent you a pull request. In which the magnifying glass icon is out of default. Please check it.

I am also looking for the next problems.
Thanks for taking the time for me.

**Comment by alistair3149** [comment] 2021-05-05 12:39
> in my idea, it is more beautiful if the magnifying glass icon is out of the default mode for right-to-left languages.
> 
> I sent you a pull request. In which the magnifying glass icon is out of default. Please check it.
> 
> I am also looking for the next problems.
> Thanks for taking the time for me.

The magnifying glass icon is purposefully not flipped because most users are right handed, therefore the handle is placed on the right hand side.

**Comment by eshagh79** [comment] 2021-05-05 12:48
Some people are also left-handed

But I will return it to the default

**Comment by alistair3149** [comment] 2021-05-05 12:52
> Some people are also left-handed
> 
> But I will return it to the default

I know but the right-handed magnifying glass is the standard for both LTR and RTL. It is not flipped because statistically more people are using magnifying glasses with their right hands no matter your language.

**Comment by eshagh79** [comment] 2021-05-05 12:57
I do not know how it was added but I know I have seen this button in some wiki pages before

![Screenshot from 2021-05-05 17-24-49](https://user-images.githubusercontent.com/52137191/117144474-3426fe80-adc7-11eb-8a96-6054f41a8b9a.png)

**Comment by alistair3149** [comment] 2021-05-05 17:25
The preference icon is indeed misaligned in larger font-size. I deployed a patch in the master and would you mind to verify if you can reproduce the issue?

**Comment by eshagh79** [comment] 2021-05-06 05:06
The location of the settings icon is now correct.
But when you move the mouse over the preferences icon and the personal menu, their background color does not match the rest of the buttons.

The method of changing the color of these buttons is really complicated. I'm even scared to look at how they work.

Why not use a fontawesome instead of an image that uses multiple filters (which cause problems) to change its color?

See the three images below.
The first is good.
![Screenshot_2021-05-06 صفحه‌های ویژه - ویکی شخصی من](https://user-images.githubusercontent.com/52137191/117244575-8828f600-ae4e-11eb-8b93-6825410a495d.png)

The latter is not good.
![Screenshot_2021-05-06 صفحه‌های ویژه - ویکی شخصی من(1)](https://user-images.githubusercontent.com/52137191/117244576-8828f600-ae4e-11eb-95f8-caf35e0e31d0.png)

The third is bad.
![Screenshot_2021-05-06 صفحه‌های ویژه - ویکی شخصی من(2)](https://user-images.githubusercontent.com/52137191/117244577-8828f600-ae4e-11eb-9b75-4fd93da17069.png)

**Comment by eshagh79** [comment] 2021-05-06 05:17
I made three changes to the code, please check them out.
1. Adjust the magnifying glass icon to show right in both right-to-left and vice versa
2. Customize the drawer button for right-to-left language.
![Screenshot_2021-05-06 صفحه‌های ویژه - ویکی شخصی من](https://user-images.githubusercontent.com/52137191/117245396-0c2fad80-ae50-11eb-8bc4-98bd45388555.png)

3. Convert ">" to "<" for the save button in the visual editor when the page width is small.
![Screenshot_2021-05-06 در حال ویرایش سیخونک های گنوم - ویکی شخصی من(1)](https://user-images.githubusercontent.com/52137191/117245402-0e920780-ae50-11eb-8fa6-92c1598f3fe8.png)

**Comment by alistair3149** [comment] 2021-05-06 14:19
> The location of the settings icon is now correct.
> But when you move the mouse over the preferences icon and the personal menu, their background color does not match the rest of the buttons.
> 
> The method of changing the color of these buttons is really complicated. I'm even scared to look at how they work.
> 
> Why not use a fontawesome instead of an image that uses multiple filters (which cause problems) to change its color?
> 
> See the three images below.
> The first is good.
> ![Screenshot_2021-05-06 صفحه‌های ویژه - ویکی شخصی من](https://user-images.githubusercontent.com/52137191/117244575-8828f600-ae4e-11eb-8b93-6825410a495d.png)
> 
> The latter is not good.
> ![Screenshot_2021-05-06 صفحه‌های ویژه - ویکی شخصی من(1)](https://user-images.githubusercontent.com/52137191/117244576-8828f600-ae4e-11eb-95f8-caf35e0e31d0.png)
> 
> The third is bad.
> ![Screenshot_2021-05-06 صفحه‌های ویژه - ویکی شخصی من(2)](https://user-images.githubusercontent.com/52137191/117244577-8828f600-ae4e-11eb-9b75-4fd93da17069.png)

Fontawesome wasn't used because it is an additional dependency and it is less flexible when you need less or more icons. Almost all of the icons yard l used in the skin are Wikimedia UI icons so it matches the rest of the MediaWiki core and extension. The drawer and the search toggle are custom CSS icons so that they can be animated. I'm planning to use animated SVG for those icons but I'm still figuring out how to use ResourceLoader to implement it properly.

As for the filter, it is to invert the SVG icon from black then apply an opacity on it so that you only need a black SVG icon to cover all the themes. I tried using the recolor option in ResourceLoader and no avail. The alternative is to embed the whole SVG but it doesn't lazyload like `background-image` so it is a performance hit in the initial load.

For the button hover state I'll look into it, it might be a bug I overlooked.

**Comment by alistair3149** [comment] 2021-05-06 14:21
> I made three changes to the code, please check them out.
> 
> 1. Adjust the magnifying glass icon to show right in both right-to-left and vice versa
> 2. Customize the drawer button for right-to-left language.
>    ![Screenshot_2021-05-06 صفحه‌های ویژه - ویکی شخصی من](https://user-images.githubusercontent.com/52137191/117245396-0c2fad80-ae50-11eb-8bc4-98bd45388555.png)
> 3. Convert ">" to "<" for the save button in the visual editor when the page width is small.
>    ![Screenshot_2021-05-06 در حال ویرایش سیخونک های گنوم - ویکی شخصی من(1)](https://user-images.githubusercontent.com/52137191/117245402-0e920780-ae50-11eb-8fa6-92c1598f3fe8.png)

The first change should already be in master, would you mind to cherry-pick the second and third patch?

**Comment by alistair3149** [comment] 2021-05-10 16:30
The hover state should be fixed for the header icons in ac2ed38. Would you mind to verify it?

**Comment by eshagh79** [comment] 2021-05-11 17:21
The problem seems to be solved.
Thankful.
One more thing: why not use the background color in the header and use the shadow box instead.
You can use linear-gradient for this. And delete extra code

**Comment by alistair3149** [comment] 2021-05-11 17:32
> The problem seems to be solved.
> Thankful.
> One more thing: why not use the background color in the header and use the shadow box instead.
> You can use linear-gradient for this. And delete extra code

Thanks for the update. We tried linear gradient before and the result was pretty bad, it does not "diffuse" to the content as nice as box shadow, that's why box shadow was picked at the end.

**Closed** 2021-10-07 15:16 UTC
Labels: bug
