### ISSUE TITLE
Skin isn't working on version 1.38.2

### ISSUE THREAD

**Issue by kizule** [StarCitizenTools/mediawiki-skins-Citizen#500] opened 2022-08-15 08:38 UTC
Hi,
skin isn't working on version 1.38.2, configuration is the default.

```
MediaWiki internal error.

Original exception: [YvoFxl-Ph2PkFk39yTMQiAABeBE] /Special:Preferences IntlException: Constructor failed
Backtrace:
from /home4/minisini/public_html/burnzero.com/skins/Citizen/includes/Partials/Drawer.php(180)
#0 /home4/minisini/public_html/burnzero.com/skins/Citizen/includes/Partials/Drawer.php(180): NumberFormatter->__construct(string, integer)
#1 /home4/minisini/public_html/burnzero.com/skins/Citizen/includes/Partials/Drawer.php(90): MediaWiki\Skins\Citizen\Partials\Drawer->getSiteStatsData()
#2 /home4/minisini/public_html/burnzero.com/skins/Citizen/includes/SkinCitizen.php(124): MediaWiki\Skins\Citizen\Partials\Drawer->getDrawerTemplateData()
#3 /home4/minisini/public_html/burnzero.com/includes/skins/SkinMustache.php(58): MediaWiki\Skins\Citizen\SkinCitizen->getTemplateData()
#4 /home4/minisini/public_html/burnzero.com/includes/skins/SkinTemplate.php(150): SkinMustache->generateHTML()
#5 /home4/minisini/public_html/burnzero.com/includes/OutputPage.php(2807): SkinTemplate->outputPage()
#6 /home4/minisini/public_html/burnzero.com/includes/MediaWiki.php(926): OutputPage->output(boolean)
#7 /home4/minisini/public_html/burnzero.com/includes/MediaWiki.php(939): MediaWiki::{closure}()
#8 /home4/minisini/public_html/burnzero.com/includes/MediaWiki.php(563): MediaWiki->main()
#9 /home4/minisini/public_html/burnzero.com/index.php(53): MediaWiki->run()
#10 /home4/minisini/public_html/burnzero.com/index.php(46): wfIndexMain()
#11 {main}

Exception caught inside exception handler: [YvoFxl-Ph2PkFk39yTMQiAABeBE] /Special:Preferences IntlException: Constructor failed
Backtrace:
from /home4/minisini/public_html/burnzero.com/skins/Citizen/includes/Partials/Drawer.php(180)
#0 /home4/minisini/public_html/burnzero.com/skins/Citizen/includes/Partials/Drawer.php(180): NumberFormatter->__construct(string, integer)
#1 /home4/minisini/public_html/burnzero.com/skins/Citizen/includes/Partials/Drawer.php(90): MediaWiki\Skins\Citizen\Partials\Drawer->getSiteStatsData()
#2 /home4/minisini/public_html/burnzero.com/skins/Citizen/includes/SkinCitizen.php(124): MediaWiki\Skins\Citizen\Partials\Drawer->getDrawerTemplateData()
#3 /home4/minisini/public_html/burnzero.com/includes/skins/SkinMustache.php(58): MediaWiki\Skins\Citizen\SkinCitizen->getTemplateData()
#4 /home4/minisini/public_html/burnzero.com/includes/skins/SkinTemplate.php(150): SkinMustache->generateHTML()
#5 /home4/minisini/public_html/burnzero.com/includes/OutputPage.php(2807): SkinTemplate->outputPage()
#6 /home4/minisini/public_html/burnzero.com/includes/exception/MWExceptionRenderer.php(157): OutputPage->output()
#7 /home4/minisini/public_html/burnzero.com/includes/exception/MWExceptionRenderer.php(76): MWExceptionRenderer::reportHTML(IntlException)
#8 /home4/minisini/public_html/burnzero.com/includes/exception/MWExceptionHandler.php(107): MWExceptionRenderer::output(IntlException, integer)
#9 /home4/minisini/public_html/burnzero.com/includes/exception/MWExceptionHandler.php(202): MWExceptionHandler::report(IntlException)
#10 /home4/minisini/public_html/burnzero.com/includes/MediaWiki.php(582): MWExceptionHandler::handleException(IntlException, string)
#11 /home4/minisini/public_html/burnzero.com/index.php(53): MediaWiki->run()
#12 /home4/minisini/public_html/burnzero.com/index.php(46): wfIndexMain()
#13 {main}
```

**Comment by kizule** [comment] 2022-08-15 09:50
I had to set $wgCitizenEnableDrawerSiteStats to false, in order to make skin work.

**Comment by alistair3149** [comment] 2022-08-15 17:13
Duplicate of #474 
It is an upstream issue that is not related to the skin, not much I can do on my end.

**Closed by alistair3149** 2022-08-15 17:13 UTC
Labels: bug
