### ISSUE TITLE
Links in infoboxes are not clickable.

### ISSUE THREAD

**Issue by Rasputin93** [StarCitizenTools/mediawiki-skins-Citizen#878] opened 2024-06-14 13:03 UTC
Just updated to 2.17.2.
Similar to after 2.17.1, there was an issue for desktop users to click on links within tables, there is also one for links in infoboxes affecting only a portion of the links found there to be simply unclickable.

Example page: https://rammwiki.net/wiki/Rammstein_(song)

Weirdly enough, the more pages with infoboxes I click (or if I reload such a page) the more clickable content appears to be rendered unclickable.

This issue does not affect the mobile view, but will apear when switching to desktop view on a mobile too.

**Comment by alistair3149** [comment] 2024-06-14 16:35
I am unable to reproduce it. What OS and browser are you using? It could have been a caching issue that can be fixed by a hard refresh as well.

**Comment by Rasputin93** [comment] 2024-06-14 16:46
I'm using the latest Firefox on both Windows and Android, our other admin uses Chrome on Apple.

Hard refresh doesn't fix it either.

Above page, all the infobox links starting from "Live debut" are not clickable. Before that, everything is fine.

**Closed** 2024-06-14 16:59 UTC
Labels: bug

**Comment by Rasputin93** [comment] 2024-06-14 17:03
After inspecting it, it appears that the "citizen-overflow-wrapper" of the neighboring table is blocking access to the links. For example the cursor won't change to the "click link" one until I reach the very top of "April 1997", despite being the very same element.
![H6fmoUaSHY](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/25199548/5052726c-4e44-41f6-878e-fe2d30f7f4ab)
