### ISSUE TITLE
MediaWiki Internal Server Error after updating to MediaWiki  version 1.38.4

### ISSUE THREAD

**Issue by Kaisa-Serian** [StarCitizenTools/mediawiki-skins-Citizen#545] opened 2022-11-15 17:26 UTC
`Original exception: [Y3PIseWpuK-CozPqgZlxFAAAWh0] /snazpedia/index.php/Main_Page IntlException: Constructor failed
Backtrace:
from /home2/vetpetmon/public_html/snazpedia/skins/Citizen/includes/Partials/Drawer.php(180)
#0 /home2/vetpetmon/public_html/snazpedia/skins/Citizen/includes/Partials/Drawer.php(180): NumberFormatter->__construct(string, integer)
#1 /home2/vetpetmon/public_html/snazpedia/skins/Citizen/includes/Partials/Drawer.php(90): MediaWiki\Skins\Citizen\Partials\Drawer->getSiteStatsData()
#2 /home2/vetpetmon/public_html/snazpedia/skins/Citizen/includes/SkinCitizen.php(120): MediaWiki\Skins\Citizen\Partials\Drawer->getDrawerTemplateData()
#3 /home2/vetpetmon/public_html/snazpedia/includes/skins/SkinMustache.php(58): MediaWiki\Skins\Citizen\SkinCitizen->getTemplateData()
#4 /home2/vetpetmon/public_html/snazpedia/includes/skins/SkinTemplate.php(150): SkinMustache->generateHTML()
#5 /home2/vetpetmon/public_html/snazpedia/includes/OutputPage.php(2807): SkinTemplate->outputPage()
#6 /home2/vetpetmon/public_html/snazpedia/includes/MediaWiki.php(926): OutputPage->output(boolean)
#7 /home2/vetpetmon/public_html/snazpedia/includes/MediaWiki.php(939): MediaWiki::{closure}()
#8 /home2/vetpetmon/public_html/snazpedia/includes/MediaWiki.php(563): MediaWiki->main()
#9 /home2/vetpetmon/public_html/snazpedia/index.php(53): MediaWiki->run()
#10 /home2/vetpetmon/public_html/snazpedia/index.php(46): wfIndexMain()
#11 {main}

Exception caught inside exception handler: [Y3PIseWpuK-CozPqgZlxFAAAWh0] /snazpedia/index.php/Main_Page IntlException: Constructor failed
Backtrace:
from /home2/vetpetmon/public_html/snazpedia/skins/Citizen/includes/Partials/Drawer.php(180)
#0 /home2/vetpetmon/public_html/snazpedia/skins/Citizen/includes/Partials/Drawer.php(180): NumberFormatter->__construct(string, integer)
#1 /home2/vetpetmon/public_html/snazpedia/skins/Citizen/includes/Partials/Drawer.php(90): MediaWiki\Skins\Citizen\Partials\Drawer->getSiteStatsData()
#2 /home2/vetpetmon/public_html/snazpedia/skins/Citizen/includes/SkinCitizen.php(120): MediaWiki\Skins\Citizen\Partials\Drawer->getDrawerTemplateData()
#3 /home2/vetpetmon/public_html/snazpedia/includes/skins/SkinMustache.php(58): MediaWiki\Skins\Citizen\SkinCitizen->getTemplateData()
#4 /home2/vetpetmon/public_html/snazpedia/includes/skins/SkinTemplate.php(150): SkinMustache->generateHTML()
#5 /home2/vetpetmon/public_html/snazpedia/includes/OutputPage.php(2807): SkinTemplate->outputPage()
#6 /home2/vetpetmon/public_html/snazpedia/includes/exception/MWExceptionRenderer.php(157): OutputPage->output()
#7 /home2/vetpetmon/public_html/snazpedia/includes/exception/MWExceptionRenderer.php(76): MWExceptionRenderer::reportHTML(IntlException)
#8 /home2/vetpetmon/public_html/snazpedia/includes/exception/MWExceptionHandler.php(107): MWExceptionRenderer::output(IntlException, integer)
#9 /home2/vetpetmon/public_html/snazpedia/includes/exception/MWExceptionHandler.php(202): MWExceptionHandler::report(IntlException)
#10 /home2/vetpetmon/public_html/snazpedia/includes/MediaWiki.php(582): MWExceptionHandler::handleException(IntlException, string)
#11 /home2/vetpetmon/public_html/snazpedia/index.php(53): MediaWiki->run()
#12 /home2/vetpetmon/public_html/snazpedia/index.php(46): wfIndexMain()
#13 {main}`

I'm filing this issue report on behalf of the SNAZpedia wiki admin. After an update to MediaWiki version 1.38.4, this error began to pop up whenever someone attempts to access the site. referencing a failed constructor with this skin's name mentioned.

**Comment by alistair3149** [comment] 2022-11-15 17:30
Your server is either missing the php-intl plugin or doesn't have it configured properly.
Alternatively, you can set `$wgCitizenUseNumberFormatter` to false to disable the localization for the stats.

Duplicate of #474

**Closed** 2022-11-15 17:30 UTC
Labels: bug
